<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CubeForge.ico</ApplicationIcon>
  </PropertyGroup>


  <ItemGroup>
    <Compile Remove="Trainers\Algorithm\**" />
    <EmbeddedResource Remove="Trainers\Algorithm\**" />
    <None Remove="Trainers\Algorithm\**" />
    <Page Remove="Trainers\Algorithm\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HelixToolkit.Wpf" Version="3.1.2" />
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks" Version="6.2.1" />
    <PackageReference Include="MaterialDesignColors" Version="5.3.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.3.0" />
  </ItemGroup>
  
  <PropertyGroup>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <PublishTrimmed>false</PublishTrimmed>
  </PropertyGroup>
  
  <ItemGroup>
    <Content Include="Data\PruningTables\**\*.bin.gz">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Assets\*.json" />
    <EmbeddedResource Include="Assets\**\*.png" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="Assets\CubeForge.ico" />
  </ItemGroup>
  
  <ItemGroup>
    <Resource Include="Assets\CubeForge.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
